# Generated by Django 5.2 on 2025-12-05 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_estimatelineitem_jobattachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='workspace.job')),
            ],
            options={
                'db_table': 'job_checklists',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workspace.jobchecklist')),
            ],
            options={
                'db_table': 'checklist_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='JobCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], default='SUBMITTED', max_length=20)),
                ('completion_notes', models.TextField(blank=True, null=True)),
                ('actual_hours_worked', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('quality_rating', models.IntegerField(blank=True, help_text='Rating 1-5', null=True)),
                ('timeliness_rating', models.IntegerField(blank=True, help_text='Rating 1-5', null=True)),
                ('professionalism_rating', models.IntegerField(blank=True, help_text='Rating 1-5', null=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_jobs', to='workspace.contractor')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='workspace.job')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_completions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('JOB_ASSIGNED', 'Job Assigned'), ('JOB_ACCEPTED', 'Job Accepted'), ('JOB_REJECTED', 'Job Rejected'), ('JOB_STARTED', 'Job Started'), ('JOB_COMPLETED', 'Job Completed'), ('JOB_VERIFIED', 'Job Verified'), ('REVISION_REQUIRED', 'Revision Required'), ('STEP_COMPLETED', 'Step Completed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspace.job')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StepMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Video'), ('DOCUMENT', 'Document')], max_length=20)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('thumbnail_path', models.CharField(blank=True, max_length=500, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='workspace.checkliststep')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'step_media',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs_by', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_assignments', to='workspace.contractor')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workspace.job')),
            ],
            options={
                'db_table': 'job_assignments',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['contractor', 'status'], name='job_assignm_contrac_3c587a_idx'), models.Index(fields=['job', 'status'], name='job_assignm_job_id_6133aa_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='checkliststep',
            index=models.Index(fields=['checklist', 'is_completed'], name='checklist_s_checkli_76f81a_idx'),
        ),
        migrations.AddIndex(
            model_name='jobnotification',
            index=models.Index(fields=['recipient', 'is_read'], name='job_notific_recipie_027265_idx'),
        ),
        migrations.AddIndex(
            model_name='jobnotification',
            index=models.Index(fields=['job', 'notification_type'], name='job_notific_job_id_4813f2_idx'),
        ),
    ]
