# Generated by Django 5.2 on 2025-12-18 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_aiconversation_angiconnection_insuranceverification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobchecklist',
            options={},
        ),
        migrations.RemoveField(
            model_name='jobchecklist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobchecklist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobchecklist',
            name='order',
        ),
        migrations.RemoveField(
            model_name='jobchecklist',
            name='title',
        ),
        migrations.AddField(
            model_name='job',
            name='brand_name',
            field=models.CharField(blank=True, default='Apex', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='evaluation_fee',
            field=models.DecimalField(decimal_places=2, default=99.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='job',
            name='evaluation_fee_credited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='expected_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expected_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='powered_by',
            field=models.CharField(blank=True, default='Apex', max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='scheduled_evaluation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobchecklist',
            name='completion_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='jobchecklist',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('LEAD', 'Lead'), ('EVALUATION_SCHEDULED', 'Evaluation Scheduled'), ('EVALUATION_COMPLETED', 'Evaluation Completed'), ('AWAITING_PRE_START_APPROVAL', 'Awaiting Pre-Start Approval'), ('IN_PROGRESS', 'In Progress'), ('MID_CHECKPOINT_PENDING', 'Mid Checkpoint Pending'), ('AWAITING_FINAL_APPROVAL', 'Awaiting Final Approval'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='LEAD', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobchecklist',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='workspace.job'),
        ),
        migrations.CreateModel(
            name='JobCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_type', models.CharField(choices=[('PRE_START', 'Pre-Start'), ('MID_PROJECT', 'Mid-Project'), ('FINAL', 'Final')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ISSUE', 'Issue')], default='PENDING', max_length=20)),
                ('scope_summary', models.TextField(blank=True, null=True)),
                ('progress_note', models.TextField(blank=True, null=True)),
                ('customer_note', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('customer_rating', models.IntegerField(blank=True, null=True)),
                ('customer_review', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='workspace.job')),
            ],
            options={
                'db_table': 'job_checkpoints',
                'ordering': ['-created_at'],
                'unique_together': {('job', 'checkpoint_type')},
            },
        ),
        migrations.CreateModel(
            name='JobEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_count', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('measurements_data', models.JSONField(blank=True, default=dict)),
                ('scope', models.TextField(blank=True, null=True)),
                ('tools_required', models.JSONField(blank=True, default=list)),
                ('labor_required', models.IntegerField(blank=True, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('safety_concerns', models.TextField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='workspace.job')),
            ],
            options={
                'db_table': 'job_evaluations',
            },
        ),
        migrations.CreateModel(
            name='JobPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('BEFORE', 'Before'), ('EVALUATION', 'Evaluation'), ('PROGRESS', 'Progress'), ('AFTER', 'After'), ('CUSTOMER_MATERIALS', 'Customer Materials')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workspace.job')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'job_photos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobProgressNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workspace.jobcheckpoint')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_notes', to='workspace.job')),
            ],
            options={
                'db_table': 'job_progress_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('gbb_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('evaluation_fee', models.DecimalField(decimal_places=2, default=99.0, max_digits=10)),
                ('total_after_credit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_items', models.JSONField(default=list)),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('generation_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='workspace.job')),
            ],
            options={
                'db_table': 'job_quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor', models.CharField(max_length=100)),
                ('vendor_logo_url', models.URLField(blank=True, null=True)),
                ('price_range', models.CharField(max_length=50)),
                ('suggested_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('product_url', models.URLField()),
                ('contractor_confirmed_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contractor_status', models.CharField(default='pending', max_length=20)),
                ('customer_material_source', models.CharField(default='links', max_length=20)),
                ('customer_liability_accepted', models.BooleanField(default=False)),
                ('contractor_verified_customer_materials', models.BooleanField(default=False)),
                ('contractor_verification_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_suggestions', to='workspace.job')),
            ],
            options={
                'db_table': 'material_suggestions',
                'ordering': ['item_name'],
            },
        ),
    ]
